version: '3.1'
services:
  db:
    image: postgres-12.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - 8964:5432


  client:
    container_name: